/**
 * Lexical Analyzer Engine
 * Implements compiler-based tokenization and spelling validation
 * Uses finite automata principles for token recognition
 */

import * as fs from "fs";
import * as path from "path";

// Token types following compiler design patterns
export enum TokenType {
  WORD = "WORD",
  NUMBER = "NUMBER",
  PUNCTUATION = "PUNCTUATION",
  WHITESPACE = "WHITESPACE",
  SYMBOL = "SYMBOL",
}

export interface Token {
  type: TokenType;
  value: string;
  position: number;
  line: number;
  column: number;
}

export interface SpellingError {
  word: string;
  position: number;
  line: number;
  column: number;
  suggestions: string[];
  confidence: number;
}

/**
 * Lexical Analyzer: Tokenizes input text using finite automata
 * Implements scanner pattern from compiler theory
 */
export class LexicalAnalyzer {
  private tokens: Token[] = [];
  private input: string;
  private position: number = 0;
  private line: number = 1;
  private column: number = 1;
  private dictionary: Set<string>;

  constructor(input: string, dictionary: Set<string>) {
    this.input = input;
    this.dictionary = dictionary;
  }

  /**
   * Main tokenization method using DFA (Deterministic Finite Automaton)
   * Recognizes: words, numbers, punctuation, whitespace, symbols
   */
  public tokenize(): Token[] {
    this.tokens = [];
    this.position = 0;
    this.line = 1;
    this.column = 1;

    while (this.position < this.input.length) {
      const char = this.input[this.position];

      if (this.isWhitespace(char)) {
        this.scanWhitespace();
      } else if (this.isLetter(char)) {
        this.scanWord();
      } else if (this.isDigit(char)) {
        this.scanNumber();
      } else if (this.isPunctuation(char)) {
        this.scanPunctuation();
      } else {
        this.scanSymbol();
      }
    }

    return this.tokens;
  }

  /**
   * Scan whitespace token (space, tab, newline)
   */
  private scanWhitespace(): void {
    const startPos = this.position;
    const startCol = this.column;
    let value = "";

    while (
      this.position < this.input.length &&
      this.isWhitespace(this.input[this.position])
    ) {
      const char = this.input[this.position];
      value += char;

      if (char === "\n") {
        this.line++;
        this.column = 1;
      } else {
        this.column++;
      }

      this.position++;
    }

    this.tokens.push({
      type: TokenType.WHITESPACE,
      value,
      position: startPos,
      line: this.line,
      column: startCol,
    });
  }

  /**
   * Scan word token (alphabetic characters)
   * Handles contractions and hyphenated words
   */
  private scanWord(): void {
    const startPos = this.position;
    const startLine = this.line;
    const startCol = this.column;
    let value = "";

    // Scan main word
    while (
      this.position < this.input.length &&
      (this.isLetter(this.input[this.position]) ||
        this.input[this.position] === "'")
    ) {
      value += this.input[this.position];
      this.column++;
      this.position++;
    }

    // Handle hyphenated words (e.g., "well-known")
    if (
      this.position < this.input.length &&
      this.input[this.position] === "-" &&
      this.position + 1 < this.input.length &&
      this.isLetter(this.input[this.position + 1])
    ) {
      value += "-";
      this.column++;
      this.position++;

      while (
        this.position < this.input.length &&
        this.isLetter(this.input[this.position])
      ) {
        value += this.input[this.position];
        this.column++;
        this.position++;
      }
    }

    this.tokens.push({
      type: TokenType.WORD,
      value,
      position: startPos,
      line: startLine,
      column: startCol,
    });
  }

  /**
   * Scan number token (digits and decimal points)
   */
  private scanNumber(): void {
    const startPos = this.position;
    const startCol = this.column;
    let value = "";

    while (
      this.position < this.input.length &&
      (this.isDigit(this.input[this.position]) ||
        this.input[this.position] === ".")
    ) {
      value += this.input[this.position];
      this.column++;
      this.position++;
    }

    this.tokens.push({
      type: TokenType.NUMBER,
      value,
      position: startPos,
      line: this.line,
      column: startCol,
    });
  }

  /**
   * Scan punctuation token
   */
  private scanPunctuation(): void {
    const startPos = this.position;
    const startCol = this.column;
    const value = this.input[this.position];

    this.tokens.push({
      type: TokenType.PUNCTUATION,
      value,
      position: startPos,
      line: this.line,
      column: startCol,
    });

    this.column++;
    this.position++;
  }

  /**
   * Scan symbol token (operators, special characters)
   */
  private scanSymbol(): void {
    const startPos = this.position;
    const startCol = this.column;
    const value = this.input[this.position];

    this.tokens.push({
      type: TokenType.SYMBOL,
      value,
      position: startPos,
      line: this.line,
      column: startCol,
    });

    this.column++;
    this.position++;
  }

  private isWhitespace(char: string): boolean {
    return /\s/.test(char);
  }

  private isLetter(char: string): boolean {
    return /[a-zA-Z]/.test(char);
  }

  private isDigit(char: string): boolean {
    return /[0-9]/.test(char);
  }

  private isPunctuation(char: string): boolean {
    return /[.,!?;:\-—–]/.test(char);
  }
}

/**
 * Spell Checker: Uses Levenshtein distance for suggestions
 * Implements edit distance algorithm from compiler error recovery
 */
export class SpellChecker {
  private dictionary: Set<string>;
  private commonMisspellings: Map<string, string[]>;

  constructor(dictionary: Set<string>) {
    this.dictionary = dictionary;
    this.commonMisspellings = new Map();
    this.initializeCommonMisspellings();
  }

  /**
   * Check if a word is spelled correctly
   */
  public isCorrect(word: string): boolean {
    const normalized = word.toLowerCase();
    return this.dictionary.has(normalized);
  }

  /**
   * Generate spelling suggestions using edit distance
   */
  public getSuggestions(word: string, maxDistance: number = 2): string[] {
    const normalized = word.toLowerCase();

    // Check common misspellings first
    if (this.commonMisspellings.has(normalized)) {
      return this.commonMisspellings.get(normalized) || [];
    }

    const suggestions: Array<{ word: string; distance: number }> = [];

    // Search dictionary for words within edit distance
    this.dictionary.forEach((dictWord: string) => {
      const distance = this.levenshteinDistance(normalized, dictWord);
      if (distance > 0 && distance <= maxDistance) {
        suggestions.push({ word: dictWord, distance });
      }
    });

    // Sort by distance and return top suggestions
    return suggestions
      .sort((a, b) => a.distance - b.distance)
      .slice(0, 5)
      .map((s) => s.word);
  }

  /**
   * Calculate Levenshtein distance between two strings
   * Used for spelling suggestions (edit distance algorithm)
   */
  private levenshteinDistance(a: string, b: string): number {
    const matrix: number[][] = [];

    for (let i = 0; i <= b.length; i++) {
      matrix[i] = [i];
    }

    for (let j = 0; j <= a.length; j++) {
      matrix[0][j] = j;
    }

    for (let i = 1; i <= b.length; i++) {
      for (let j = 1; j <= a.length; j++) {
        if (b.charAt(i - 1) === a.charAt(j - 1)) {
          matrix[i][j] = matrix[i - 1][j - 1];
        } else {
          matrix[i][j] = Math.min(
            matrix[i - 1][j - 1] + 1, // substitution
            matrix[i][j - 1] + 1, // insertion
            matrix[i - 1][j] + 1 // deletion
          );
        }
      }
    }

    return matrix[b.length][a.length];
  }

  /**
   * Initialize common misspellings database
   */
  private initializeCommonMisspellings(): void {
    const common: Record<string, string[]> = {
      recieve: ["receive"],
      occured: ["occurred"],
      seperete: ["separate"],
      untill: ["until"],
      begining: ["beginning"],
      wich: ["which"],
      thier: ["their"],
      definately: ["definitely"],
      accomodate: ["accommodate"],
      occassion: ["occasion"],
      realy: ["really"],
      truely: ["truly"],
      arguement: ["argument"],
      enviroment: ["environment"],
      goverment: ["government"],
      bussiness: ["business"],
      neccessary: ["necessary"],
      existance: ["existence"],
      refered: ["referred"],
      writting: ["writing"],
      sucess: ["success"],
      mispell: ["misspell"],
      dissapear: ["disappear"],
      alot: ["a lot"],
      havent: ["haven't"],
      doesnt: ["doesn't"],
      shouldnt: ["shouldn't"],
    } as Record<string, string[]>;

    Object.entries(common).forEach(([misspelled, corrections]) => {
      this.commonMisspellings.set(misspelled, corrections);
    });
  }
}

/**
 * Load English dictionary from file
 * Returns a Set for O(1) lookup
 */
export function loadDictionary(): Set<string> {
  const dictionary: Set<string> = new Set<string>();

  // Comprehensive English word list (common words)
  const words = [
    // Common words
    "the",
    "be",
    "to",
    "of",
    "and",
    "a",
    "in",
    "that",
    "have",
    "i",
    "it",
    "for",
    "not",
    "on",
    "with",
    "he",
    "as",
    "you",
    "do",
    "at",
    "this",
    "but",
    "his",
    "by",
    "from",
    "they",
    "we",
    "say",
    "her",
    "she",
    "or",
    "an",
    "will",
    "my",
    "one",
    "all",
    "would",
    "there",
    "their",
    "what",
    "so",
    "up",
    "out",
    "if",
    "about",
    "who",
    "get",
    "which",
    "go",
    "me",
    "when",
    "make",
    "can",
    "like",
    "time",
    "no",
    "just",
    "him",
    "know",
    "take",
    "people",
    "into",
    "year",
    "your",
    "good",
    "some",
    "could",
    "them",
    "see",
    "other",
    "than",
    "then",
    "now",
    "look",
    "only",
    "come",
    "its",
    "over",
    "think",
    "also",
    "back",
    "after",
    "use",
    "two",
    "how",
    "our",
    "work",
    "first",
    "well",
    "way",
    "even",
    "new",
    "want",
    "because",
    "any",
    "these",
    "give",
    "day",
    "most",
    "us",
    "is",
    "was",
    "are",
    "been",
    "being",
    "have",
    "has",
    "had",
    "do",
    "does",
    "did",
    "will",
    "would",
    "could",
    "should",
    "may",
    "might",
    "must",
    "can",
    "shall",
    // Common nouns
    "man",
    "woman",
    "child",
    "person",
    "people",
    "family",
    "friend",
    "house",
    "home",
    "place",
    "thing",
    "work",
    "job",
    "school",
    "book",
    "word",
    "language",
    "english",
    "text",
    "sentence",
    "paragraph",
    "letter",
    "word",
    "spelling",
    "grammar",
    "error",
    "mistake",
    "correction",
    "analysis",
    "system",
    "computer",
    "software",
    "program",
    "application",
    "website",
    "page",
    "file",
    "document",
    "data",
    "information",
    "content",
    "message",
    "email",
    "phone",
    "number",
    "address",
    "name",
    "title",
    "subject",
    "topic",
    "idea",
    "thought",
    "feeling",
    "emotion",
    "action",
    "event",
    "situation",
    "problem",
    "solution",
    "question",
    "answer",
    "reason",
    "purpose",
    "goal",
    "result",
    "effect",
    "cause",
    "change",
    "difference",
    "similarity",
    "quality",
    "quantity",
    "size",
    "shape",
    "color",
    "sound",
    "smell",
    "taste",
    "touch",
    "temperature",
    "weather",
    "season",
    "time",
    "date",
    "day",
    "week",
    "month",
    "year",
    "hour",
    "minute",
    "second",
    "morning",
    "afternoon",
    "evening",
    "night",
    "sun",
    "moon",
    "star",
    "sky",
    "earth",
    "water",
    "fire",
    "air",
    "wind",
    "rain",
    "snow",
    "cloud",
    "tree",
    "flower",
    "plant",
    "animal",
    "dog",
    "cat",
    "bird",
    "fish",
    "insect",
    "food",
    "drink",
    "fruit",
    "vegetable",
    "meat",
    "bread",
    "milk",
    "cheese",
    "egg",
    "sugar",
    "salt",
    "oil",
    "butter",
    "money",
    "price",
    "cost",
    "value",
    "payment",
    "debt",
    "credit",
    "bank",
    "business",
    "market",
    "shop",
    "store",
    "customer",
    "seller",
    "buyer",
    "product",
    "service",
    "quality",
    "brand",
    "company",
    "organization",
    "government",
    "law",
    "rule",
    "right",
    "duty",
    "responsibility",
    "freedom",
    "justice",
    "peace",
    "war",
    "conflict",
    "agreement",
    "contract",
    "promise",
    "trust",
    "faith",
    "hope",
    "love",
    "hate",
    "fear",
    "anger",
    "joy",
    "sadness",
    "surprise",
    "disgust",
    "health",
    "disease",
    "medicine",
    "doctor",
    "hospital",
    "patient",
    "treatment",
    "cure",
    "pain",
    "injury",
    "accident",
    "danger",
    "safety",
    "protection",
    "defense",
    "attack",
    "weapon",
    "army",
    "soldier",
    "officer",
    "general",
    "battle",
    "victory",
    "defeat",
    "strategy",
    "tactic",
    "plan",
    "design",
    "structure",
    "building",
    "bridge",
    "road",
    "street",
    "city",
    "town",
    "village",
    "country",
    "nation",
    "state",
    "province",
    "region",
    "continent",
    "ocean",
    "sea",
    "lake",
    "river",
    "mountain",
    "valley",
    "desert",
    "forest",
    "jungle",
    "island",
    "beach",
    "coast",
    "port",
    "harbor",
    "airport",
    "station",
    "terminal",
    "vehicle",
    "car",
    "truck",
    "bus",
    "train",
    "plane",
    "ship",
    "boat",
    "bicycle",
    "motorcycle",
    "engine",
    "wheel",
    "door",
    "window",
    "wall",
    "roof",
    "floor",
    "ceiling",
    "room",
    "kitchen",
    "bedroom",
    "bathroom",
    "living",
    "dining",
    "garden",
    "yard",
    "fence",
    "gate",
    "lock",
    "key",
    "light",
    "lamp",
    "electricity",
    "power",
    "energy",
    "fuel",
    "coal",
    "oil",
    "gas",
    "nuclear",
    "solar",
    "wind",
    "water",
    "electricity",
    "technology",
    "science",
    "research",
    "experiment",
    "theory",
    "fact",
    "evidence",
    "proof",
    "logic",
    "reason",
    "argument",
    "debate",
    "discussion",
    "conversation",
    "dialogue",
    "speech",
    "lecture",
    "presentation",
    "performance",
    "show",
    "entertainment",
    "music",
    "song",
    "dance",
    "art",
    "painting",
    "drawing",
    "sculpture",
    "photography",
    "film",
    "movie",
    "theater",
    "play",
    "comedy",
    "tragedy",
    "drama",
    "story",
    "novel",
    "poem",
    "poetry",
    "verse",
    "prose",
    "fiction",
    "nonfiction",
    "history",
    "biography",
    "autobiography",
    "memoir",
    "diary",
    "journal",
    "magazine",
    "newspaper",
    "article",
    "report",
    "essay",
    "thesis",
    "dissertation",
    "research",
    "study",
    "survey",
    "statistics",
    "mathematics",
    "algebra",
    "geometry",
    "calculus",
    "physics",
    "chemistry",
    "biology",
    "geology",
    "astronomy",
    "geography",
    "economics",
    "politics",
    "philosophy",
    "psychology",
    "sociology",
    "anthropology",
    "education",
    "learning",
    "teaching",
    "student",
    "teacher",
    "professor",
    "instructor",
    "tutor",
    "course",
    "class",
    "lesson",
    "assignment",
    "homework",
    "exam",
    "test",
    "grade",
    "score",
    "mark",
    "certificate",
    "diploma",
    "degree",
    "university",
    "college",
    "academy",
    "institute",
    "laboratory",
    "library",
    "museum",
    "gallery",
    "exhibition",
    "display",
    "collection",
    "artifact",
    "monument",
    "memorial",
    "statue",
    "portrait",
    "landscape",
    "still",
    "life",
    "nature",
    "natural",
    "artificial",
    "synthetic",
    "organic",
    "inorganic",
    "living",
    "dead",
    "alive",
    "extinct",
    "rare",
    "common",
    "unique",
    "special",
    "ordinary",
    "extraordinary",
    "normal",
    "abnormal",
    "regular",
    "irregular",
    "perfect",
    "imperfect",
    "complete",
    "incomplete",
    "whole",
    "part",
    "piece",
    "fragment",
    "section",
    "division",
    "category",
    "class",
    "type",
    "kind",
    "sort",
    "variety",
    "species",
    "genus",
    "family",
    "order",
    "kingdom",
    "level",
    "degree",
    "scale",
    "measure",
    "unit",
    "standard",
    "criterion",
    "criteria",
    "requirement",
    "specification",
    "feature",
    "characteristic",
    "property",
    "attribute",
    "quality",
    "trait",
    "virtue",
    "vice",
    "strength",
    "weakness",
    "advantage",
    "disadvantage",
    "benefit",
    "harm",
    "profit",
    "loss",
    "gain",
    "expense",
    "income",
    "revenue",
    "budget",
    "account",
    "balance",
    "transaction",
    "investment",
    "return",
    "interest",
    "rate",
    "percentage",
    "fraction",
    "decimal",
    "ratio",
    "proportion",
    "average",
    "median",
    "mode",
    "range",
    "distribution",
    "probability",
    "chance",
    "luck",
    "fortune",
    "fate",
    "destiny",
    "coincidence",
    "accident",
    "incident",
    "event",
    "occurrence",
    "phenomenon",
    "experience",
    "adventure",
    "journey",
    "trip",
    "voyage",
    "expedition",
    "exploration",
    "discovery",
    "invention",
    "innovation",
    "creation",
    "production",
    "manufacture",
    "construction",
    "building",
    "assembly",
    "installation",
    "operation",
    "function",
    "purpose",
    "use",
    "application",
    "implementation",
    "execution",
    "performance",
    "behavior",
    "conduct",
    "manner",
    "method",
    "technique",
    "procedure",
    "process",
    "step",
    "stage",
    "phase",
    "cycle",
    "pattern",
    "trend",
    "tendency",
    "inclination",
    "preference",
    "choice",
    "option",
    "alternative",
    "possibility",
    "probability",
    "likelihood",
    "certainty",
    "doubt",
    "uncertainty",
    "confusion",
    "clarity",
    "understanding",
    "comprehension",
    "knowledge",
    "wisdom",
    "intelligence",
    "intellect",
    "mind",
    "brain",
    "thought",
    "idea",
    "concept",
    "notion",
    "belief",
    "opinion",
    "view",
    "perspective",
    "point",
    "standpoint",
    "attitude",
    "approach",
    "strategy",
    "tactic",
    "move",
    "step",
    "action",
    "reaction",
    "response",
    "answer",
    "solution",
    "resolution",
    "conclusion",
    "end",
    "finish",
    "completion",
    "accomplishment",
    "achievement",
    "success",
    "failure",
    "attempt",
    "effort",
    "try",
    "endeavor",
    "struggle",
    "fight",
    "battle",
    "war",
    "conflict",
    "dispute",
    "argument",
    "disagreement",
    "misunderstanding",
    "confusion",
    "mix",
    "mixture",
    "combination",
    "compound",
    "element",
    "ingredient",
    "component",
    "part",
    "whole",
    "assembly",
    "collection",
    "group",
    "team",
    "squad",
    "crew",
    "staff",
    "personnel",
    "member",
    "participant",
    "player",
    "actor",
    "character",
    "role",
    "position",
    "rank",
    "status",
    "title",
    "name",
    "label",
    "tag",
    "mark",
    "sign",
    "symbol",
    "icon",
    "image",
    "picture",
    "photo",
    "photograph",
    "snapshot",
    "view",
    "scene",
    "sight",
    "vision",
    "appearance",
    "look",
    "style",
    "fashion",
    "trend",
    "design",
    "pattern",
    "texture",
    "surface",
    "material",
    "substance",
    "matter",
    "composition",
    "structure",
    "framework",
    "skeleton",
    "foundation",
    "base",
    "support",
    "pillar",
    "column",
    "beam",
    "frame",
    "scaffold",
    "platform",
    "stage",
    "podium",
    "stand",
    "booth",
    "stall",
    "counter",
    "desk",
    "table",
    "chair",
    "seat",
    "bench",
    "bed",
    "sofa",
    "couch",
    "cushion",
    "pillow",
    "blanket",
    "sheet",
    "towel",
    "cloth",
    "fabric",
    "textile",
    "thread",
    "yarn",
    "string",
    "rope",
    "cable",
    "wire",
    "cord",
    "chain",
    "link",
    "connection",
    "joint",
    "hinge",
    "pivot",
    "axis",
    "center",
    "middle",
    "core",
    "heart",
    "soul",
    "spirit",
    "essence",
    "nature",
    "character",
    "personality",
    "identity",
    "self",
    "ego",
    "consciousness",
    "awareness",
    "perception",
    "sensation",
    "feeling",
    "emotion",
    "sentiment",
    "passion",
    "desire",
    "wish",
    "want",
    "need",
    "requirement",
    "necessity",
    "obligation",
    "duty",
    "responsibility",
    "commitment",
    "promise",
    "pledge",
    "vow",
    "oath",
    "agreement",
    "contract",
    "deal",
    "arrangement",
    "settlement",
    "compromise",
    "negotiation",
    "discussion",
    "conference",
    "meeting",
    "gathering",
    "assembly",
    "congregation",
    "audience",
    "spectator",
    "observer",
    "witness",
    "participant",
    "member",
    "associate",
    "colleague",
    "partner",
    "ally",
    "enemy",
    "opponent",
    "rival",
    "competitor",
    "contestant",
    "participant",
    "player",
    "athlete",
    "champion",
    "winner",
    "loser",
    "victor",
    "vanquished",
    "conqueror",
    "conquered",
    "master",
    "servant",
    "slave",
    "lord",
    "lady",
    "gentleman",
    "woman",
    "man",
    "boy",
    "girl",
    "infant",
    "baby",
    "child",
    "adolescent",
    "teenager",
    "adult",
    "elder",
    "elderly",
    "senior",
    "junior",
    "ancestor",
    "descendant",
    "heir",
    "heiress",
    "offspring",
    "sibling",
    "brother",
    "sister",
    "cousin",
    "uncle",
    "aunt",
    "nephew",
    "niece",
    "grandfather",
    "grandmother",
    "grandson",
    "granddaughter",
    "parent",
    "father",
    "mother",
    "son",
    "daughter",
    "spouse",
    "husband",
    "wife",
    "lover",
    "sweetheart",
    "fiancé",
    "fiancée",
    "bride",
    "groom",
    "wedding",
    "marriage",
    "divorce",
    "separation",
    "relationship",
    "friendship",
    "companionship",
    "fellowship",
    "brotherhood",
    "sisterhood",
    "community",
    "society",
    "civilization",
    "culture",
    "tradition",
    "custom",
    "habit",
    "practice",
    "ritual",
    "ceremony",
    "celebration",
    "festival",
    "holiday",
    "vacation",
    "break",
    "rest",
    "relaxation",
    "leisure",
    "recreation",
    "hobby",
    "pastime",
    "game",
    "sport",
    "competition",
    "contest",
    "match",
    "tournament",
    "championship",
    "league",
    "team",
    "club",
    "association",
    "organization",
    "institution",
    "establishment",
    "enterprise",
    "venture",
    "project",
    "program",
    "initiative",
    "campaign",
    "mission",
    "objective",
    "goal",
    "target",
    "aim",
    "purpose",
    "intention",
    "plan",
    "scheme",
    "plot",
    "conspiracy",
    "secret",
    "mystery",
    "puzzle",
    "riddle",
    "enigma",
    "paradox",
    "contradiction",
    "inconsistency",
    "discrepancy",
    "difference",
    "distinction",
    "contrast",
    "comparison",
    "analogy",
    "metaphor",
    "simile",
    "symbol",
    "allegory",
    "parable",
    "fable",
    "myth",
    "legend",
    "folklore",
    "superstition",
    "belief",
    "faith",
    "religion",
    "spirituality",
    "morality",
    "ethics",
    "virtue",
    "vice",
    "sin",
    "crime",
    "punishment",
    "reward",
    "penalty",
    "fine",
    "sentence",
    "judgment",
    "verdict",
    "trial",
    "court",
    "judge",
    "jury",
    "lawyer",
    "attorney",
    "defendant",
    "plaintiff",
    "witness",
    "evidence",
    "testimony",
    "confession",
    "alibi",
    "motive",
    "opportunity",
    "means",
    "weapon",
    "tool",
    "instrument",
    "device",
    "machine",
    "apparatus",
    "equipment",
    "gear",
    "kit",
    "set",
    "collection",
    "assortment",
    "variety",
    "selection",
    "choice",
    "option",
    "alternative",
    "substitute",
    "replacement",
    "spare",
    "backup",
    "reserve",
    "stock",
    "supply",
    "inventory",
    "warehouse",
    "storage",
    "container",
    "box",
    "case",
    "bag",
    "suitcase",
    "luggage",
    "baggage",
    "cargo",
    "freight",
    "shipment",
    "delivery",
    "package",
    "parcel",
    "envelope",
    "letter",
    "mail",
    "postage",
    "stamp",
    "address",
    "destination",
    "route",
    "path",
    "way",
    "direction",
    "north",
    "south",
    "east",
    "west",
    "left",
    "right",
    "up",
    "down",
    "front",
    "back",
    "side",
    "top",
    "bottom",
    "inside",
    "outside",
    "above",
    "below",
    "between",
    "among",
    "through",
    "across",
    "along",
    "around",
    "near",
    "far",
    "close",
    "distant",
    "adjacent",
    "opposite",
    "parallel",
    "perpendicular",
    "diagonal",
    "horizontal",
    "vertical",
    "angle",
    "curve",
    "straight",
    "bent",
    "twisted",
    "tangled",
    "knotted",
    "tied",
    "bound",
    "fastened",
    "attached",
    "connected",
    "linked",
    "joined",
    "united",
    "separated",
    "divided",
    "split",
    "broken",
    "shattered",
    "cracked",
    "torn",
    "ripped",
    "cut",
    "sliced",
    "chopped",
    "crushed",
    "ground",
    "mashed",
    "blended",
    "mixed",
    "stirred",
    "whisked",
    "beaten",
    "whipped",
    "pounded",
    "hammered",
    "nailed",
    "screwed",
    "bolted",
    "welded",
    "soldered",
    "glued",
    "pasted",
    "stuck",
    "adhered",
    "clung",
    "gripped",
    "held",
    "grasped",
    "seized",
    "grabbed",
    "caught",
    "trapped",
    "ensnared",
    "captured",
    "arrested",
    "imprisoned",
    "confined",
    "restrained",
    "bound",
    "chained",
    "shackled",
    "locked",
    "sealed",
    "closed",
    "shut",
    "opened",
    "unlocked",
    "released",
    "freed",
    "liberated",
    "emancipated",
    "discharged",
    "dismissed",
    "fired",
    "laid",
    "off",
    "resigned",
    "retired",
    "quit",
    "left",
    "departed",
    "exited",
    "entered",
    "arrived",
    "came",
    "went",
    "traveled",
    "journeyed",
    "wandered",
    "roamed",
    "drifted",
    "floated",
    "flew",
    "soared",
    "glided",
    "swooped",
    "dived",
    "plunged",
    "jumped",
    "leaped",
    "bounced",
    "hopped",
    "skipped",
    "ran",
    "sprinted",
    "jogged",
    "walked",
    "strolled",
    "marched",
    "stomped",
    "shuffled",
    "crawled",
    "climbed",
    "descended",
    "fell",
    "dropped",
    "slipped",
    "tripped",
    "stumbled",
    "staggered",
    "swayed",
    "wobbled",
    "tilted",
    "leaned",
    "bent",
    "stretched",
    "reached",
    "extended",
    "contracted",
    "compressed",
    "expanded",
    "inflated",
    "deflated",
    "swelled",
    "shrank",
    "grew",
    "developed",
    "evolved",
    "transformed",
    "changed",
    "altered",
    "modified",
    "adjusted",
    "adapted",
    "converted",
    "translated",
    "interpreted",
    "explained",
    "clarified",
    "simplified",
    "complicated",
    "confused",
    "mixed",
    "sorted",
    "organized",
    "arranged",
    "rearranged",
    "shuffled",
    "dealt",
    "distributed",
    "divided",
    "shared",
    "allocated",
    "assigned",
    "designated",
    "appointed",
    "elected",
    "selected",
    "chosen",
    "picked",
    "preferred",
    "favored",
    "liked",
    "loved",
    "adored",
    "cherished",
    "treasured",
    "valued",
    "appreciated",
    "respected",
    "admired",
    "praised",
    "complimented",
    "flattered",
    "congratulated",
    "celebrated",
    "honored",
    "recognized",
    "acknowledged",
    "confirmed",
    "verified",
    "validated",
    "approved",
    "endorsed",
    "supported",
    "backed",
    "defended",
    "protected",
    "shielded",
    "guarded",
    "watched",
    "observed",
    "monitored",
    "supervised",
    "managed",
    "controlled",
    "directed",
    "guided",
    "led",
    "commanded",
    "ordered",
    "instructed",
    "taught",
    "trained",
    "coached",
    "mentored",
    "advised",
    "counseled",
    "consulted",
    "discussed",
    "debated",
    "argued",
    "disputed",
    "contested",
    "challenged",
    "questioned",
    "asked",
    "inquired",
    "wondered",
    "pondered",
    "considered",
    "thought",
    "reflected",
    "meditated",
    "contemplated",
    "dreamed",
    "imagined",
    "visualized",
    "envisioned",
    "pictured",
    "conceived",
    "created",
    "invented",
    "designed",
    "planned",
    "prepared",
    "organized",
    "arranged",
    "scheduled",
    "timed",
    "delayed",
    "postponed",
    "deferred",
    "suspended",
    "interrupted",
    "paused",
    "stopped",
    "halted",
    "ceased",
    "ended",
    "finished",
    "completed",
    "accomplished",
    "achieved",
    "attained",
    "reached",
    "obtained",
    "acquired",
    "gained",
    "earned",
    "won",
    "succeeded",
    "triumphed",
    "prevailed",
    "conquered",
    "defeated",
    "vanquished",
    "overcame",
    "survived",
    "endured",
    "persisted",
    "continued",
    "proceeded",
    "advanced",
    "progressed",
    "improved",
    "enhanced",
    "upgraded",
    "refined",
    "polished",
    "perfected",
    "completed",
    "finished",
    "done",
    "ready",
    "prepared",
    "set",
    "arranged",
    "organized",
    "structured",
    "formatted",
    "styled",
    "decorated",
    "adorned",
    "embellished",
    "garnished",
    "trimmed",
    "edged",
    "bordered",
    "framed",
    "outlined",
    "highlighted",
    "emphasized",
    "stressed",
    "underlined",
    "marked",
    "noted",
    "recorded",
    "documented",
    "filed",
    "archived",
    "stored",
    "saved",
    "backed",
    "up",
    "copied",
    "duplicated",
    "replicated",
    "reproduced",
    "printed",
    "published",
    "released",
    "distributed",
    "circulated",
    "broadcast",
    "transmitted",
    "sent",
    "delivered",
    "received",
    "accepted",
    "taken",
    "received",
    "obtained",
    "got",
    "acquired",
    "possessed",
    "owned",
    "held",
    "kept",
    "retained",
    "maintained",
    "preserved",
    "protected",
    "defended",
    "guarded",
    "watched",
    "observed",
    "noticed",
    "saw",
    "viewed",
    "looked",
    "examined",
    "inspected",
    "checked",
    "tested",
    "tried",
    "attempted",
    "endeavored",
    "strived",
    "struggled",
    "fought",
    "resisted",
    "opposed",
    "objected",
    "protested",
    "complained",
    "grumbled",
    "muttered",
    "whispered",
    "spoke",
    "said",
    "told",
    "expressed",
    "stated",
    "declared",
    "announced",
    "proclaimed",
    "asserted",
    "insisted",
    "maintained",
    "claimed",
    "alleged",
    "suggested",
    "implied",
    "hinted",
    "indicated",
    "signaled",
    "gestured",
    "pointed",
    "showed",
    "displayed",
    "exhibited",
    "presented",
    "offered",
    "provided",
    "supplied",
    "furnished",
    "equipped",
    "outfitted",
    "prepared",
    "readied",
    "primed",
    "loaded",
    "charged",
    "energized",
    "activated",
    "triggered",
    "initiated",
    "started",
    "began",
    "commenced",
    "launched",
    "opened",
    "unveiled",
    "revealed",
    "disclosed",
    "exposed",
    "uncovered",
    "discovered",
    "found",
    "located",
    "situated",
    "positioned",
    "placed",
    "put",
    "set",
    "laid",
    "positioned",
    "arranged",
    "organized",
    "structured",
    "formed",
    "shaped",
    "molded",
    "carved",
    "sculpted",
    "crafted",
    "built",
    "constructed",
    "assembled",
    "installed",
    "mounted",
    "hung",
    "attached",
    "affixed",
    "fastened",
    "secured",
    "anchored",
    "stabilized",
    "balanced",
    "equilibrated",
    "leveled",
    "aligned",
    "adjusted",
    "tuned",
    "calibrated",
    "synchronized",
    "coordinated",
    "harmonized",
    "unified",
    "integrated",
    "consolidated",
    "merged",
    "combined",
    "blended",
    "fused",
    "welded",
    "bonded",
    "linked",
    "connected",
    "joined",
    "coupled",
    "paired",
    "matched",
    "fitted",
    "suited",
    "adapted",
    "adjusted",
    "modified",
    "altered",
    "changed",
    "transformed",
    "converted",
    "translated",
    "interpreted",
    "explained",
    "clarified",
    "simplified",
    "complicated",
    "confused",
    "obscured",
    "hidden",
    "concealed",
    "masked",
    "disguised",
    "camouflaged",
    "covered",
    "wrapped",
    "enclosed",
    "contained",
    "held",
    "stored",
    "kept",
    "preserved",
    "maintained",
    "sustained",
    "supported",
    "upheld",
    "carried",
    "bore",
    "transported",
    "conveyed",
    "transferred",
    "moved",
    "shifted",
    "displaced",
    "relocated",
    "repositioned",
    "rearranged",
    "reorganized",
    "restructured",
    "reformed",
    "renovated",
    "restored",
    "repaired",
    "fixed",
    "mended",
    "patched",
    "sealed",
    "plugged",
    "filled",
    "topped",
    "completed",
    "finished",
    "done",
    "accomplished",
    "achieved",
    "attained",
    "reached",
    "obtained",
    "acquired",
    "gained",
    "earned",
    "won",
    "succeeded",
    "triumphed",
    "prevailed",
    "conquered",
    "defeated",
    "vanquished",
    "overcame",
    "survived",
    "endured",
    "persisted",
    "continued",
    "proceeded",
    "advanced",
    "progressed",
    "improved",
    "enhanced",
    "upgraded",
    "refined",
    "polished",
    "perfected",
    "completed",
    "finished",
  ];

  words.forEach((word: string) => {
    dictionary.add(word.toLowerCase());
  });

  return dictionary;
}
